#
# File: \config\services.yaml
# Author: Peter Nagy <peter@antronin.consulting>
# -----
# Copyright (c) 2023-2026 Antronin Consulting Ltd.
# ----------	---	---------------------------------------------------------
#
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Antronin-Consulting\PswCompositionBundle\:
        resource: '../src/'

    antronin_consulting_psw_composition.validator.constraints.psw_composition:
        class: Antronin-Consulting\PswCompositionBundle\Validator\PswComposition
        tags: [ 'validator.constraint_validator' ]
