#
# File: \config\services.yaml
# Author: Peter Nagy <peter@antronin.consulting>
# -----
# Copyright (c) 2023-2026 Antronin Consulting Ltd.
# ----------	---	---------------------------------------------------------
#
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Antronin\PswCompositionBundle\:
        resource: '../src/'

    antronin_psw_composition.validator.psw_composition:
        class: Antronin\PswCompositionBundle\Validator\PswCompositionValidator
        tags: [ 'validator.constraint_validator' ]
